### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by Engineero**
I made some changes for compatibility with Python 3. Mostly I got rid of the `long` keyword anywhere that it appears in `lib/spanlib/` files (all integers are long and covered by `int` in Python 3), and I got rid of the `cmp` argument to `list.sort()`, which is no longer supported in Python 3. I don't know the library well enough to thoroughly test it, but if I come across bugs I will try to fix them and create a new pull request.

Also, this could just be my system, but I found that I had to run `autoconf` before running `./configure`, and that `./configure` never worked for me. I was able to get `python setup.py install` to work, along with `python build_ext --inplace`, which I added to the README.

### CODE REVIEW

**Comment by stefraynaud** [comment]
Excellent!
I'll check that next week.

I think I will remove the pure fortran+autotools support and focus on the python interface.

**Comment by Engineero** [comment]
Great. I noticed that there is an error now in analyzer.py when I try to run PCA. I have not needed to use this so I haven't figured it out yet, but the error is in line 359 of `data.py`:

```python
firstdims = tuple([(isinstance(a, int)  and a or len(a)) for a in firstaxes])
```

It has an issue with `len(a)` when `a` is a scalar I think. I will try to fix this and update my branch, but I thought I'd let you know in case you see an obvious solution. I am still not sure what this line is checking.

**Review by stefraynaud — APPROVED** [review]

**Comment by stefraynaud** [comment]
@Engineero do you also use the fortran version by itself or always through the python interface?

**Comment by Engineero** [comment]
@stefraynaud I always just used the Python interface. No familiarity with the Fortran side, sorry.

**Pull request merged**
